title: Secure by AK
tagline: Offensive Security | Penetration Testing | Red Teaming
description: >
  Cybersecurity consultant specializing in offensive security, red teaming, and infrastructure testing.
url: https://securebyak.com
baseurl: ""

lang: en
timezone: America/Halifax

theme: jekyll-theme-chirpy

github:
  username: abhishekk-cyber

social:
  name: Abhishek Kumar
  email: abhishekk.cyber@gmail.com
  links:
    - https://github.com/abhishekk-cyber
    - https://www.linkedin.com/in/abhishekkcyber/

toc: true
paginate: 10
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
# trigger rebuild
